# common.env
services:
  market_data:
    build:
      context: .
      dockerfile: ./services/market_data/Dockerfile
    env_file:
      - common.env
  strategy:
    build:
      context: .
      dockerfile: ./services/strategy/Dockerfile
    env_file:
      - common.env
    environment:
      - MKT_HOST=market_data
      - EX_HOST=execution
    depends_on:
      - market_data
      - execution
  execution:
    build:
      context: .
      dockerfile: ./services/execution/Dockerfile
    env_file:
      - common.env
    environment:
      - MKT_HOST=market_data
    depends_on:
      - market_data
  portfolio:
    build:
      context: .
      dockerfile: ./services/portfolio/Dockerfile
    env_file:
      - common.env
    environment:
      - MKT_HOST=market_data
      - EX_HOST=execution
    ports:
      - 50053:50053
    depends_on:
      - market_data
      - execution